
dist: xenial

language: python
python:
    - 3.7

before_install:
- sudo apt-get install -y graphviz  

install: 
    pip install scipy pandas sklearn xgboost lightgbm jupyter matplotlib pydot graphviz

script: 
    - mkdir -p logs
    - python ./tests/display_version_info.py
    - python ./tests/sample.py
    - python ./tests/sample_reg.py
    - make PYTHON=python -f tests/Makefile build-test
    - python scripts/upload_to_curldu.mp.py
    - pip install .
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/sample_demo.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/DecisionTree-explain-plot.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/sample_DecisionTree-custom-binning.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/sample_DecisionTree-scorecard.ipynb 
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/sklearn_reason_codes.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute doc/sklearn_reason_codes_RandomForest.ipynb
